use serde::{Deserialize, Serialize};

/// High-level data socket types used for connecting workflow nodes
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SocketType {
    /// Directory containing FASTA/FASTQ sequence files
    SequenceFolder,
    /// Individual FASTA file
    FastaFile,
    /// Paired FASTQ files (R1 & R2)
    FastqPair,
    /// Output report generated by ResFinder
    #[serde(rename = "resfinder_report", alias = "res_finder_report")]
    ResFinderReport,
    /// Generic Tabular/TSV data
    TabularReport,
    /// Generic/Wildcard socket
    Any,
}

impl SocketType {
    /// Checks if a source socket type can connect to a target socket type
    pub fn can_connect_to(&self, target: &SocketType) -> bool {
        if *self == SocketType::Any || *target == SocketType::Any {
            return true;
        }
        self == target
    }
}

/// Port direction on a node
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum PortDirection {
    Input,
    Output,
}

/// A connectable socket port on a node
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Port {
    pub id: String,
    pub name: String,
    pub socket_type: SocketType,
    pub direction: PortDirection,
}

/// The architectural kind of workflow node
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", content = "tool_id", rename_all = "snake_case")]
pub enum NodeKind {
    /// Ingestion node: selects a local folder of sequence files
    FolderInput,
    /// Processing node: runs an isolated bioinformatics tool
    Tool(String),
    /// Sink node: saves or exports outputs
    OutputSave,
}

/// A node instantiated on the workflow canvas
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct WorkflowNode {
    pub id: String,
    pub kind: NodeKind,
    pub title: String,
    #[serde(default)]
    pub inputs: Vec<Port>,
    #[serde(default)]
    pub outputs: Vec<Port>,
    #[serde(default)]
    pub params: serde_json::Value,
    #[serde(default)]
    pub position: (f32, f32),
}

/// A directed edge connecting an output port of a source node to an input port of a target node
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct WorkflowEdge {
    pub id: String,
    pub source_node: String,
    pub source_port: String,
    pub target_node: String,
    pub target_port: String,
}

/// Complete workflow graph
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct WorkflowGraph {
    pub nodes: Vec<WorkflowNode>,
    pub edges: Vec<WorkflowEdge>,
}

impl WorkflowGraph {
    pub fn new() -> Self {
        Self::default()
    }

    /// Creates the standard 3-node ResFinder workflow graph
    pub fn template_resfinder() -> Self {
        let node_input = WorkflowNode {
            id: "node_input".to_string(),
            kind: NodeKind::FolderInput,
            title: "Folder Input".to_string(),
            inputs: vec![],
            outputs: vec![Port {
                id: "sequence_files".to_string(),
                name: "Sequence Files".to_string(),
                socket_type: SocketType::SequenceFolder,
                direction: PortDirection::Output,
            }],
            params: serde_json::json!({
                "directory_path": "",
                "file_pattern": "*.fasta,*.fna,*.fa,*.fastq",
            }),
            position: (50.0, 150.0),
        };

        let node_resfinder = WorkflowNode {
            id: "node_resfinder".to_string(),
            kind: NodeKind::Tool("resfinder".to_string()),
            title: "ResFinder 4.4.2".to_string(),
            inputs: vec![Port {
                id: "input_files".to_string(),
                name: "Sequence Files".to_string(),
                socket_type: SocketType::SequenceFolder,
                direction: PortDirection::Input,
            }],
            outputs: vec![Port {
                id: "resfinder_report".to_string(),
                name: "ResFinder Report".to_string(),
                socket_type: SocketType::ResFinderReport,
                direction: PortDirection::Output,
            }],
            params: serde_json::json!({
                "threshold": 0.90,
                "min_cov": 0.60,
                "species": "other",
                "acquired": true,
                "point": false,
            }),
            position: (420.0, 150.0),
        };

        let node_output = WorkflowNode {
            id: "node_output".to_string(),
            kind: NodeKind::OutputSave,
            title: "Output Save".to_string(),
            inputs: vec![Port {
                id: "results".to_string(),
                name: "ResFinder Report".to_string(),
                socket_type: SocketType::ResFinderReport,
                direction: PortDirection::Input,
            }],
            outputs: vec![],
            params: serde_json::json!({
                "destination_dir": "",
                "export_format": "tsv",
                "auto_open": true,
            }),
            position: (790.0, 150.0),
        };

        let edges = vec![
            WorkflowEdge {
                id: "e_input_to_rf".to_string(),
                source_node: "node_input".to_string(),
                source_port: "sequence_files".to_string(),
                target_node: "node_resfinder".to_string(),
                target_port: "input_files".to_string(),
            },
            WorkflowEdge {
                id: "e_rf_to_output".to_string(),
                source_node: "node_resfinder".to_string(),
                source_port: "resfinder_report".to_string(),
                target_node: "node_output".to_string(),
                target_port: "results".to_string(),
            },
        ];

        Self {
            nodes: vec![node_input, node_resfinder, node_output],
            edges,
        }
    }
}
