/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ExtensionsRouteImport } from './routes/extensions'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as ExploreCollectionRouteImport } from './routes/explore.collection'
import { Route as ExploreDownloadsRouteImport } from './routes/explore.downloads'
import { Route as ExploreSearchRouteImport } from './routes/explore.search'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsRoute = ExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreCollectionRoute = ExploreCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreDownloadsRoute = ExploreDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreSearchRoute = ExploreSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ExploreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRouteWithChildren
  '/extensions': typeof ExtensionsRoute
  '/results': typeof ResultsRoute
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/workflow': typeof WorkflowRoute
  '/explore/collection': typeof ExploreCollectionRoute
  '/explore/downloads': typeof ExploreDownloadsRoute
  '/explore/search': typeof ExploreSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRouteWithChildren
  '/extensions': typeof ExtensionsRoute
  '/results': typeof ResultsRoute
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/workflow': typeof WorkflowRoute
  '/explore/collection': typeof ExploreCollectionRoute
  '/explore/downloads': typeof ExploreDownloadsRoute
  '/explore/search': typeof ExploreSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRouteWithChildren
  '/extensions': typeof ExtensionsRoute
  '/results': typeof ResultsRoute
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/workflow': typeof WorkflowRoute
  '/explore/collection': typeof ExploreCollectionRoute
  '/explore/downloads': typeof ExploreDownloadsRoute
  '/explore/search': typeof ExploreSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/extensions'
    | '/results'
    | '/runs'
    | '/settings'
    | '/workflow'
    | '/explore/collection'
    | '/explore/downloads'
    | '/explore/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/extensions'
    | '/results'
    | '/runs'
    | '/settings'
    | '/workflow'
    | '/explore/collection'
    | '/explore/downloads'
    | '/explore/search'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/extensions'
    | '/results'
    | '/runs'
    | '/settings'
    | '/workflow'
    | '/explore/collection'
    | '/explore/downloads'
    | '/explore/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRouteWithChildren
  ExtensionsRoute: typeof ExtensionsRoute
  ResultsRoute: typeof ResultsRoute
  RunsRoute: typeof RunsRoute
  SettingsRoute: typeof SettingsRoute
  WorkflowRoute: typeof WorkflowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions': {
      id: '/extensions'
      path: '/extensions'
      fullPath: '/extensions'
      preLoaderRoute: typeof ExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/collection': {
      id: '/explore/collection'
      path: '/collection'
      fullPath: '/explore/collection'
      preLoaderRoute: typeof ExploreCollectionRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/downloads': {
      id: '/explore/downloads'
      path: '/downloads'
      fullPath: '/explore/downloads'
      preLoaderRoute: typeof ExploreDownloadsRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/search': {
      id: '/explore/search'
      path: '/search'
      fullPath: '/explore/search'
      preLoaderRoute: typeof ExploreSearchRouteImport
      parentRoute: typeof ExploreRoute
    }
  }
}

interface ExploreRouteChildren {
  ExploreCollectionRoute: typeof ExploreCollectionRoute
  ExploreDownloadsRoute: typeof ExploreDownloadsRoute
  ExploreSearchRoute: typeof ExploreSearchRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreCollectionRoute: ExploreCollectionRoute,
  ExploreDownloadsRoute: ExploreDownloadsRoute,
  ExploreSearchRoute: ExploreSearchRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRouteWithChildren,
  ExtensionsRoute: ExtensionsRoute,
  ResultsRoute: ResultsRoute,
  RunsRoute: RunsRoute,
  SettingsRoute: SettingsRoute,
  WorkflowRoute: WorkflowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
